### ISSUE TITLE
大佬，非常期待的v2ray的实现

### ISSUE THREAD

**Issue by Shameless521** [duanhai/Tun2socks-mobile-demo#1]
大佬，非常期待的v2ray的实现

**Comment by Shameless521** [comment]
go-tun2socks-mobile/tun2socks.go:23:50: too many arguments in call to socks.NewTCPHandler
go-tun2socks-mobile/tun2socks.go:24:50: too many arguments in call to socks.NewUDPHandler

大佬，我用go-tun2socks-mobile 打包一直包这个错误，不知道怎么解决。
能否告知一下

**Comment by duanhai** [comment]
对应的go方法变了，调整下参数个数就好

**Comment by duanhai** [comment]
之前@eycorsican 在go-tun2socks-ios *.go中有写过v2ray的func；后面在xxx-mobile最新版本中对应的实现好像删除了。
