### ISSUE TITLE
SIOCGIFMTU failed: Device not configured

### ISSUE THREAD

**Issue by Shameless521** [duanhai/Tun2socks-mobile-demo#2]
运行后，服务起不来，包这个错误
SIOCGIFMTU failed: Device not configured
NEVirtualInterfaceAdjustReadBufferSize: interface_get_mtu failed (6), defaulting to max mtu

**Comment by tozik** [comment]
> 运行后，服务起不来，包这个错误 SIOCGIFMTU failed: Device not configured NEVirtualInterfaceAdjustReadBufferSize: interface_get_mtu failed (6), defaulting to max mtu

@Shameless521 how did you solve it?

**Comment by hosseinkhojany** [comment]
@tozik are you solve it bro ?

**Comment by tozik** [comment]
@hosseinkhojany i've change library

**Comment by hosseinkhojany** [comment]
Man, I'm really disappointed with Mac OS. Steve Jobs should come to my aid 
@tozik 
![Screenshot 2023-08-21 at 12 14 07 PM](https://github.com/duanhai/Tun2socks-PacketTunnelDemo/assets/37432839/60930541-6392-4e70-8f1e-f1ae17964835)

**Comment by hosseinkhojany** [comment]
@tozik 
Brother, if you have been able to bypass upstream in Mac OS, you can help me 
SOS!!!!!!!!!!!!!!
