### ISSUE TITLE
大佬，开关开启后，切换出去，会断掉

### ISSUE THREAD

**Issue by Shameless521** [duanhai/Tun2socks-mobile-demo#3]
Last disconnect error changed from "none" to "The VPN session failed because an internal error occurred."

进程控制台会报错

`{
    "outbounds": [
        {
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "xxxx",
                        "port": 443,
                        "users": [
                            {
                                "id": "xxxxxxxxxxxxxx",
                                "alterId": 12,
                                "security": "auto"
                            }
                        ]
                    }
                ]
            },
            "streamSettings":{
                "network":"ws",
                "security":"tls",
                "tlssettings":{
                    "allowInsecure":true,
                    "serverName":""
                },
                "wssettings":{
                    "connectionReuse":true,
                    "headers":{
                        "Host":""
                    },
                    "path":"/help"
                }
            }
        }
    ]
    
    
}
`
这个是我的配置文件，还是翻不了，请问大佬这是什么情况啊？

是否需要导入匹配规则

**Comment by duanhai** [comment]
1，配置文件，你看我的readme里面有个模板，还是代码里面有个模板，我当时也是遇到报错，只保留了个最简单的就没出现
2，会断的可能是内存大于15M了，没有仔细去跟怎么优化

**Comment by Shameless521** [comment]
大佬，那你用简单的能用了么？

**Comment by duanhai** [comment]
可以用，放油管可以，刷网页内存就爆了

**Comment by Shameless521** [comment]
大佬你的那个是tcp 还是kcp？
