### ISSUE TITLE
大佬，问下服务器参数

### ISSUE THREAD

**Issue by Shameless521** [duanhai/Tun2socks-mobile-demo#4]
大佬，麻烦问下，按照您的这个demo， 服务器的参数怎么配置，能不能给我一个例子。有tls ws协议这快么？

**Comment by huang-ju** [comment]
@Shameless521 你解决了吗？同有这个疑问

**Comment by duanhai** [comment]
https://github.com/233boy/v2ray/wiki/V2Ray%E4%B8%80%E9%94%AE%E5%AE%89%E8%A3%85%E8%84%9A%E6%9C%AC

**Comment by sqzxcv** [comment]
你这个版本不支持tls, ws协议把?
