### ISSUE TITLE
在哪里调用startTunnel？

### ISSUE THREAD

**Issue by huang-ju** [duanhai/Tun2socks-mobile-demo#5]
你的demo我无法运行，我根据你的demo写了一个类似的，但没见到你在哪有调用startTunnel？

还有在设置中会提示“v2ray需要更新”，这是什么原因？v2ray-core版本过低？

**Comment by duanhai** [comment]
VpnManager.shared.connect() 触发 startTunnel，看下VpnManager的方法，都是模板化调用。这个Demo主要是想展示packetflow 怎么调用。v2ray的配置，根据其它的repo做调整，设置中提示需要更新的，我不太明白你想表达的意思，可以po图。

**Comment by huang-ju** [comment]
![6291570521904_ pic](https://user-images.githubusercontent.com/46550127/66378121-6f8ffa00-e9e5-11e9-97f0-c80a7f293804.jpg)

提示需要更新

**Comment by duanhai** [comment]
检查下你的代码，是不是描述部分写的

**Comment by huang-ju** [comment]
![6301570525899_ pic_hd](https://user-images.githubusercontent.com/46550127/66382959-b6362200-e9ee-11e9-9a0c-24dd96ac7e5d.jpg)

你的demo无法运行在设备中，这是什么原因？
