### ISSUE TITLE
一直显示连接中，怎样能看到打印的信息？

### ISSUE THREAD

**Issue by huang-ju** [duanhai/Tun2socks-mobile-demo#7]
![image](https://user-images.githubusercontent.com/46550127/66416094-af7bcf00-ea2f-11e9-8c8a-08d9e8f6d0d5.png)

开启服务后，一直显示正在连接，这是什么原因？怎样我才能看到我打印的内容进行调试？

**Comment by sych520** [comment]
有联系方式吗？ 想咨询一下v2ray的问题  我的QQ： 461170711，可以加我一下
