### ISSUE TITLE
配置正常 连接了无法翻墙

### ISSUE THREAD

**Issue by azhm** [duanhai/Tun2socks-mobile-demo#8]
请问配置好json 正常连接后无法翻墙 是需要配置什么路由吗

**Comment by azhm** [comment]
我设置了streamSettings即可使用了

**Comment by sych520** [comment]
哥位，你好，能加我一下QQ,问你一下这方面的问题吗？ QQ:461170711

**Comment by lil-hope** [comment]
你好怎么配置的想问下

**Comment by mousezc** [comment]
> 我设置了streamSettings即可使用了

你好我想问一下你是怎么配置的我也是连接之后无法翻墙 streamSettings这个在哪设置
